theme = "zed_onedark"

[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true
color-modes = true
scrolloff = 8
auto-format = false
text-width = 120
completion-timeout = 100
completion-trigger-len = 1
insert-final-newline = false
end-of-line-diagnostics = "disable"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-inlay-hints = true
display-progress-messages = true

[editor.statusline]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]